As a Planning editor I like to use “advanced templates” for events [SDESK-6746]
superdesk/superdesk-planning pull request #1905
Opened 2024-01-30 16:41 UTC by devketanpro

2024-01-31 01:21 UTC, MarkLark86 requested changes

2024-01-31 01:21 UTC, MarkLark86 commented on client/actions/main.ts
> +    const embeddedPlanning = template.data?.embedded_planning || [];
This check can be done in the `getEventsAssociatedItems` function, and return empty array if not defined

2024-01-31 04:35 UTC, MarkLark86 commented on client/actions/events/api.ts
> +                        embedded_planning: item.associated_plannings.map((planning) => ({
@devketanpro Please disregard this one. I'll need to do it anyways in my current task

2024-01-31 09:03 UTC, devketanpro commented on server/planning/events/events_template.py
> +    allow_unknown = True
makes sense

2024-01-31 23:20 UTC, MarkLark86 commented on server/planning/events/events_template.py
> +    _event_fields.setdefault("embedded_planning", events_schema["embedded_planning"])
No need to use `setdefault` here, you can just place it underneath the `subject` entry above :point_up:

2024-02-01 05:01 UTC, MarkLark86 approved these changes

2024-02-13 08:45 UTC, merged